# Secret Manager KMS設定
apiVersion: secretmanager.googleapis.com/v1
kind: Secret
metadata:
  name: openai-api-key
  project: PROJECT_ID
spec:
  replication:
    userManaged:
      replicas:
      - location: asia-northeast1
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring/cryptoKeys/openai-key
      - location: asia-northeast2
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast2/keyRings/therapeutic-app-keyring/cryptoKeys/openai-key
  labels:
    app: therapeutic-gamification
    environment: production
    sensitivity: high

---
apiVersion: secretmanager.googleapis.com/v1
kind: Secret
metadata:
  name: line-channel-secret
  project: PROJECT_ID
spec:
  replication:
    userManaged:
      replicas:
      - location: asia-northeast1
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring/cryptoKeys/line-key
      - location: asia-northeast2
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast2/keyRings/therapeutic-app-keyring/cryptoKeys/line-key

---
apiVersion: secretmanager.googleapis.com/v1
kind: Secret
metadata:
  name: jwt-secret
  project: PROJECT_ID
spec:
  replication:
    userManaged:
      replicas:
      - location: asia-northeast1
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring/cryptoKeys/jwt-key
      - location: asia-northeast2
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast2/keyRings/therapeutic-app-keyring/cryptoKeys/jwt-key

---
apiVersion: secretmanager.googleapis.com/v1
kind: Secret
metadata:
  name: stripe-secret-key
  project: PROJECT_ID
spec:
  replication:
    userManaged:
      replicas:
      - location: asia-northeast1
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring/cryptoKeys/stripe-key
      - location: asia-northeast2
        customerManagedEncryption:
          kmsKeyName: projects/PROJECT_ID/locations/asia-northeast2/keyRings/therapeutic-app-keyring/cryptoKeys/stripe-key

---
# KMSキーリング設定
apiVersion: cloudkms.googleapis.com/v1
kind: KeyRing
metadata:
  name: therapeutic-app-keyring
  location: asia-northeast1
  project: PROJECT_ID

---
# 暗号化キー設定
apiVersion: cloudkms.googleapis.com/v1
kind: CryptoKey
metadata:
  name: openai-key
  parent: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring
spec:
  purpose: ENCRYPT_DECRYPT
  versionTemplate:
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    protectionLevel: SOFTWARE
  rotationPeriod: 7776000s  # 90日
  nextRotationTime: "2024-04-01T00:00:00Z"
  labels:
    service: openai
    environment: production

---
apiVersion: cloudkms.googleapis.com/v1
kind: CryptoKey
metadata:
  name: line-key
  parent: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring
spec:
  purpose: ENCRYPT_DECRYPT
  versionTemplate:
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    protectionLevel: SOFTWARE
  rotationPeriod: 7776000s  # 90日

---
apiVersion: cloudkms.googleapis.com/v1
kind: CryptoKey
metadata:
  name: jwt-key
  parent: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring
spec:
  purpose: ENCRYPT_DECRYPT
  versionTemplate:
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    protectionLevel: SOFTWARE
  rotationPeriod: 2592000s  # 30日（JWT用は短期間）

---
apiVersion: cloudkms.googleapis.com/v1
kind: CryptoKey
metadata:
  name: stripe-key
  parent: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring
spec:
  purpose: ENCRYPT_DECRYPT
  versionTemplate:
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
    protectionLevel: SOFTWARE
  rotationPeriod: 7776000s  # 90日

---
# IAM設定
apiVersion: iam.googleapis.com/v1
kind: Policy
metadata:
  resource: projects/PROJECT_ID/locations/asia-northeast1/keyRings/therapeutic-app-keyring/cryptoKeys/openai-key
spec:
  bindings:
  - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
    members:
    - serviceAccount:therapeutic-app-service-account@PROJECT_ID.iam.gserviceaccount.com
  - role: roles/cloudkms.viewer
    members:
    - serviceAccount:therapeutic-app-service-account@PROJECT_ID.iam.gserviceaccount.com